#include "../src/history_belief_exclusion.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>

static void require(int condition, const char *message)
{
    if (!condition) {
        fprintf(stderr, "test_history_belief_exclusion: %s\n", message);
        exit(EXIT_FAILURE);
    }
}

static int free_card_named(const char *name, uint64_t used)
{
    char shown[8];
    for (int card = 0; card < NCARD; card++) {
        lc_card_name(card, shown);
        if (!strcasecmp(shown, name) &&
            !(used & (UINT64_C(1) << card)))
            return card;
    }
    return -1;
}

/* Audit-only fixture loader.  Campaign generation has no saved-state input;
 * this parser exists solely to compare the extracted module against a locked
 * exact-17 digest generated by policy_cost_dataset's native hash-probe. */
static int load_fixture(const char *path, State *state)
{
    FILE *file = fopen(path, "r");
    if (!file) return 0;
    memset(state, 0, sizeof *state);
    uint64_t used = 0;
    char line[512];
    while (fgets(line, sizeof line, file)) {
        char *token = strtok(line, " \t\n");
        if (!token) continue;
        if (!strcmp(token, "turn") || !strcmp(token, "round") ||
            !strcmp(token, "nply") || !strcmp(token, "deck_left")) {
            char *value = strtok(NULL, " \t\n");
            if (!value || strtok(NULL, " \t\n")) goto invalid;
            int parsed = atoi(value);
            if (!strcmp(token, "turn")) state->turn = (uint8_t)parsed;
            else if (!strcmp(token, "round")) state->round = (uint8_t)parsed;
            else if (!strcmp(token, "nply")) state->nply = (uint16_t)parsed;
            else state->deck_left = (uint8_t)parsed;
        } else if (!strcmp(token, "cum")) {
            char *a = strtok(NULL, " \t\n");
            char *b = strtok(NULL, " \t\n");
            if (!a || !b || strtok(NULL, " \t\n")) goto invalid;
            state->cum[0] = (int16_t)atoi(a);
            state->cum[1] = (int16_t)atoi(b);
        } else if (!strncmp(token, "hand", 4) &&
                   token[4] >= '0' && token[4] <= '1' && !token[5]) {
            int player = token[4] - '0';
            char *word;
            while ((word = strtok(NULL, " \t\n"))) {
                int card = free_card_named(word, used);
                if (card < 0) goto invalid;
                used |= UINT64_C(1) << card;
                state->hand[player] |= UINT64_C(1) << card;
                state->hand_n[player]++;
            }
        } else if (!strncmp(token, "known", 5) &&
                   token[5] >= '0' && token[5] <= '1' && !token[6]) {
            int player = token[5] - '0';
            char *word;
            while ((word = strtok(NULL, " \t\n"))) {
                char shown[8];
                int found = 0;
                for (int card = 0; card < NCARD; card++) {
                    lc_card_name(card, shown);
                    if (!strcasecmp(shown, word) &&
                        (state->hand[player] &
                            (UINT64_C(1) << card)) &&
                        !(state->known[player] &
                            (UINT64_C(1) << card))) {
                        state->known[player] |= UINT64_C(1) << card;
                        found = 1;
                        break;
                    }
                }
                if (!found) goto invalid;
            }
        } else if (!strcmp(token, "exp")) {
            char *ptext = strtok(NULL, " \t\n");
            char *stext = strtok(NULL, " \t\n");
            if (!ptext || !stext) goto invalid;
            int player = atoi(ptext), suit = atoi(stext);
            if (player < 0 || player > 1 || suit < 0 || suit >= NSUIT)
                goto invalid;
            char *word;
            while ((word = strtok(NULL, " \t\n"))) {
                int card = free_card_named(word, used);
                if (card < 0 || CARD_SUIT(card) != suit) goto invalid;
                used |= UINT64_C(1) << card;
                state->played[player] |= UINT64_C(1) << card;
                state->exp_n[player][suit]++;
                if (CARD_IS_WAGER(card)) state->exp_wager[player][suit]++;
                else {
                    int value = CARD_VALUE(card);
                    if (value > state->exp_top[player][suit])
                        state->exp_top[player][suit] = (uint8_t)value;
                    state->exp_sum[player][suit] = (uint8_t)(
                        state->exp_sum[player][suit] + value);
                }
            }
        } else if (!strcmp(token, "pile")) {
            char *stext = strtok(NULL, " \t\n");
            if (!stext) goto invalid;
            int suit = atoi(stext);
            if (suit < 0 || suit >= NSUIT) goto invalid;
            char *word;
            while ((word = strtok(NULL, " \t\n"))) {
                int card = free_card_named(word, used);
                if (card < 0 || CARD_SUIT(card) != suit ||
                    state->pile_n[suit] >= NRANK)
                    goto invalid;
                used |= UINT64_C(1) << card;
                state->pile[suit][state->pile_n[suit]++] = (uint8_t)card;
                state->discarded |= UINT64_C(1) << card;
            }
        } else {
            goto invalid;
        }
    }
    if (ferror(file) || fclose(file) != 0) return 0;
    return state->turn <= 1 && state->round < MATCH_ROUNDS &&
           state->hand_n[0] == HAND_SIZE &&
           state->hand_n[1] == HAND_SIZE;

invalid:
    fclose(file);
    return 0;
}

int main(void)
{
    static const char manifest_path[] =
        "data/experiments/policy_cost_v7_exact17_exclusions.txt";
    static const char *const reviewed_paths[HISTORY_BELIEF_EXCLUSION_COUNT] = {
        "data/probes/ui_seed2214615196_p3.state",
        "data/probes/ui_seed2214615196_p4.state",
        "data/probes/ui_seed2214615196_p8.state",
        "data/probes/ui_seed2214615196_p10.state",
        "data/probes/ui_seed2214615196_p12.state",
        "data/probes/ui_seed2214615196_p13.state",
        "data/probes/ui_seed2214615196_p16.state",
        "data/probes/ui_seed2214615196_p20.state",
        "data/probes/showcase_5726968372613385_p14.state",
        "data/probes/showcase_5726968372613385_p15.state",
        "data/probes/showcase_5726968372613385_p17.state",
        "data/probes/showcase_5726968372613385_p32.state",
        "data/probes/ui_seed725402798_p21.state",
        "data/probes/ui_seed725402798_p22.state",
        "data/probes/ui_seed725402798_p23.state",
        "data/probes/ui_seed725402798_p25.state",
        "data/probes/ui_seed95647345759839_p44.state",
    };
    HistoryBeliefExclusions exclusions;
    require(history_belief_exclusions_load(
                manifest_path, HISTORY_BELIEF_EXACT17_CANONICAL_SHA256,
                &exclusions),
            "canonical exact-17 manifest did not load");
    require(exclusions.count == HISTORY_BELIEF_EXCLUSION_COUNT &&
            !strcmp(exclusions.manifest_sha256_hex,
                    HISTORY_BELIEF_EXACT17_CANONICAL_SHA256),
            "loaded manifest binding changed");

    HistoryBeliefExclusions rejected = exclusions;
    require(!history_belief_exclusions_load(
                manifest_path,
                "0000000000000000000000000000000000000000000000000000000000000000",
                &rejected) && rejected.count == 0 &&
            rejected.manifest_sha256_hex[0] == '\0',
            "wrong SHA-256 binding did not fail closed");
    require(!history_belief_exclusions_load(
                manifest_path,
                "10034CF8B83AADF24FA0775E4DAD2712573E1D84CBF364568CE6136682AC254C",
                &rejected),
            "noncanonical uppercase SHA-256 binding was accepted");

    State reviewed[HISTORY_BELIEF_EXCLUSION_COUNT];
    for (int index = 0; index < HISTORY_BELIEF_EXCLUSION_COUNT; index++) {
        unsigned char candidate_orbit[32];
        require(load_fixture(reviewed_paths[index], &reviewed[index]),
                "could not load a locked exact-17 fixture");
        require(history_belief_exclusion_orbit(
                    &reviewed[index], reviewed[index].turn,
                    candidate_orbit) &&
                !memcmp(candidate_orbit, exclusions.orbit[index],
                        sizeof candidate_orbit) &&
                history_belief_exclusions_check(
                    &exclusions, &reviewed[index], reviewed[index].turn,
                    NULL) == 1,
                "exact-17 orbit drifted from the locked native manifest");
    }

    State p3 = reviewed[0];
    unsigned char orbit[32];
    require(history_belief_exclusion_orbit(&p3, p3.turn, orbit) &&
            !memcmp(orbit, exclusions.orbit[0], sizeof orbit),
            "locked p3 orbit changed after all-17 verification");

    uint8_t permutation[NSUIT] = { 3, 0, 4, 1, 2 };
    State relabelled;
    lc_permute_suits(&p3, &relabelled, permutation);
    unsigned char relabelled_orbit[32];
    require(history_belief_exclusion_orbit(
                &relabelled, relabelled.turn, relabelled_orbit) &&
            !memcmp(orbit, relabelled_orbit, sizeof orbit) &&
            history_belief_exclusions_check(
                &exclusions, &relabelled, relabelled.turn, NULL) == 1,
            "suit-equivalent reviewed position escaped exclusion");

    /* Challenge every hidden byte/field independently.  The firewall-local
     * projector must not read any deck byte, deck position, or opponent-hand
     * bit before it decides whether this reviewed orbit is excluded. */
    int opponent = p3.turn ^ 1;
    unsigned char alternate_orbit[32];
    for (int index = 0; index < NCARD; index++) {
        State hidden = p3;
        hidden.deck[index] = (uint8_t)(index + 1);
        require(history_belief_exclusion_orbit(
                    &hidden, hidden.turn, alternate_orbit) &&
                !memcmp(orbit, alternate_orbit, sizeof orbit),
                "a hidden deck byte contaminated the exclusion orbit");
    }
    State hidden = p3;
    hidden.deck_pos = UINT8_MAX;
    require(history_belief_exclusion_orbit(
                &hidden, hidden.turn, alternate_orbit) &&
            !memcmp(orbit, alternate_orbit, sizeof orbit),
            "hidden deck position contaminated the exclusion orbit");
    for (int bit = 0; bit < 64; bit++) {
        hidden = p3;
        hidden.hand[opponent] ^= UINT64_C(1) << bit;
        require(history_belief_exclusion_orbit(
                    &hidden, hidden.turn, alternate_orbit) &&
                !memcmp(orbit, alternate_orbit, sizeof orbit),
                "an opponent private-hand bit contaminated the exclusion orbit");
    }

    /* Physical wager identity is deliberately collapsed. */
    State alternate_wager = p3;
    int player = p3.turn;
    uint64_t public_or_held = alternate_wager.hand[0] |
                              alternate_wager.hand[1] |
                              alternate_wager.played[0] |
                              alternate_wager.played[1] |
                              alternate_wager.discarded;
    int wager = -1, replacement = -1;
    for (int card = 0; card < NCARD && wager < 0; card++)
        if ((alternate_wager.hand[player] & (UINT64_C(1) << card)) &&
            CARD_IS_WAGER(card)) wager = card;
    require(wager >= 0, "fixture mover had no wager");
    int suit = CARD_SUIT(wager);
    for (int rank = 0; rank < WAGERS_PER_SUIT; rank++) {
        int card = CARD_MAKE(suit, rank);
        if (!(public_or_held & (UINT64_C(1) << card))) {
            replacement = card;
            break;
        }
    }
    require(replacement >= 0, "could not swap physical wager identity");
    alternate_wager.hand[player] &= ~(UINT64_C(1) << wager);
    alternate_wager.hand[player] |= UINT64_C(1) << replacement;
    require(history_belief_exclusion_orbit(
                &alternate_wager, alternate_wager.turn, alternate_orbit) &&
            !memcmp(orbit, alternate_orbit, sizeof orbit),
            "physical wager identity changed semantic orbit");

    Rng rng;
    rng_seed(&rng, UINT64_C(202706290103));
    State ordinary;
    lc_deal(&ordinary, &rng);
    require(history_belief_exclusions_check(
                &exclusions, &ordinary, ordinary.turn, NULL) == 0,
            "ordinary generated state collided with reviewed set");
    require(history_belief_exclusions_check(
                &exclusions, &ordinary, ordinary.turn ^ 1, NULL) == -1,
            "non-mover observer did not fail closed");
    ordinary.over = 1;
    require(history_belief_exclusions_check(
                &exclusions, &ordinary, ordinary.turn, NULL) == -1,
            "terminal state did not fail closed");
    HistoryBeliefExclusions empty = {0};
    require(history_belief_exclusions_check(
                &empty, &p3, p3.turn, NULL) == -1,
            "unbound manifest did not fail closed");

    puts("history_belief_exclusion tests: ok");
    return 0;
}
